### ISSUE TITLE
[backend] Основная страница

### ISSUE THREAD

**Issue by LeraChernyakova** [moevm/nosql2h24-plants#28]
Добавить в модель растения поле "sold_at": ISODate(). По умолчанию данное поле не заполнено. Если оно не null, значит, растение продали/обменяли, и на основной странице при запросе GET /api/plants его отображать не надо.

---
При выполнении запроса GET /api/plants - получении всех растений, необходимо добавить в возвращаемый ответ еще одно поле - "id" растения

---
Реализовать пагинацию.
Выбрать количество отображаемых растений, например, по 15 на странице.
Номер текущей страницы приходит как query параметр GET /api/plants под названием page

---
Реализовать сортировку.
Принцип сортировки приходит как query параметр GET /api/plants под названием sort.
Варианты:
cheaper
expensive
date
Данные типа "string".

---
Реализовать фильтрацию. Запрос будет приходить GET /api/plants.
Фильтр приходит как query параметр.
Примеры фильтров:
```
"species": "string",
"type": "string",
"size": arrayOf("string"),
"light_condition": arrayOf("string"),
"watering_frequency": arrayOf("string"),
"temperature_regime": arrayOf("string"),
"care_complexity": arrayOf("string"),
"description": "string",
"place": "string",
"price_begin": float, //цена от
"price_end": float // цена до
```
Учитывать, что не все из данных полей могут быть заполнены, перечислен случай, когда заполнили все поля.
Для полей, где только один элемент типа "string" (требование от Марк Марковича):
>_поиск в любых текстовых полях обязательно регистронезависимый и по подстроке (не по полному совпадению)_

---
Учитывать комбинацию фильтрации, пагинации и сортировки.

---
Реализовать поиск. Запрос также приходит как query параметр GET /api/plants. Параметр будет называться "search" и будет типа "string".
Поиск может также комбинироваться с фильтрацией, пагинацией, сортировкой.

**Comment by AnjeZenda** [comment]
Добавление пагинаций для всех ручек

Вместо GET фильтрации будет использован POST фильтрация, так как разнообразие фильтров лучше передавать в body а не в query
