### ISSUE TITLE
[backend] активные и архивные объявления пользователя

### ISSUE THREAD

**Issue by LeraChernyakova** [moevm/nosql2h24-plants#36]
Активные
GET /api/plants/active/{user_id}
Архивные
GET /api/plants/archive/{user_id}
Проверка активного объявления происходит по полю "sold_at". Если оно пустое/null - активное, иначе архивное

**Comment by AnjeZenda** [comment]
sold_at представляется непустым значением
В случае непроданного растения является 0 значением для времени
