### ISSUE TITLE
[backend] Реализация отображения статистики

### ISSUE THREAD

**Issue by LeraChernyakova** [moevm/nosql2h24-plants#71]
Необходимо реализовать получение данных для отображения статистики.

1. Количество опубликованных растений за указанный период времени
REST: /api/statistic/plants
Отправляю временной период С какого включительно По какой включительно нужны следующие данные:
- Сколько всего найдено элементов
- Основное: вернуть все различные species + если растений с одним species несколько, то их число
Отбор данных производим по полю created_at

2. Количество совершенных продаж
REST: /api/statistic/buy
Отправляю временной период С какого включительно По какой включительно нужны следующие данные:
- Сколько всего найдено элементов
- Дни, когда были проданы одно растение и больше + сколько продали
Отбор производить по полю created в trade +  из trade учитываем только то, что имеет тип buy

3. Количество обменов
REST: /api/statistic/trade
Отправляю временной период С какого включительно По какой включительно.
Здесь отбор происходит в коллекции trade по полю updated_at.
Нужно знать для каждого дня в промежутке:
- Количество trade со статусом 1
- Количество trade со статусом 2
- Количество trade со статусом 3
Если трейда с каким-то статусом нет (то есть 0 элементов - не возвращать его)
+Сколько всего найдено элементов

**Comment by AnjeZenda** [comment]
🤔😐

**Comment by LeraChernyakova** [comment]
Это будет POST запрос, который я кидаю вида `/api/statistic/${this.statType}`
И тело запроса
{
startDate: this.dateFrom,
endDate: this.dateTo
}

**Comment by LeraChernyakova** [comment]
Предположительный вид response
Статистика по plants
```
{
 statistic: [
{
"species": "...",
"count": ...
},
{}
],
count: ИТОГО СКОЛЬКО НАШЛОСЬ, по факту сумма мелких count
}
```

Статистика по tarde
```
{
 statistic: [
{
"date": дата в любом формате,
"pend": ... (count > 0),
"accept": ... (count > 0),
"reject": ... (count > 0)
},
{}
],
count: ИТОГО СКОЛЬКО НАШЛОСЬ, по факту сумма мелких count
}
```

Статистика по buy
```
{
 statistic: [
{
"date": дата в любом формате,
"count": ... (count > 0)
},
{}
],
count: ИТОГО СКОЛЬКО НАШЛОСЬ, по факту сумма мелких count
}
```
