### ISSUE TITLE
[backend] Продажа растений

### ISSUE THREAD

**Issue by LeraChernyakova** [moevm/nosql2h24-plants#8]
1)Реализация получения данных о растениях из коллекции plants. Начальное отображение на странице. Макет пункт 2.
backend + работа с базой данных
Запрос будет следующий: GET /api/plants
Мне нужны только следующие поля из коллекции plants: img, species, price, created_at, place(нет в бд, добавить, это город, где продаем)

2)Реализация добавления на продажу растения. Макет пункт 5.
backend + работа с базой данных
Запрос будет следующий: POST /api/plants/add
Буду отправлять следующее в коллекцию Plants
{
  "img"
  "place"
  "size": "string",               // Размер растения
  "price": "number",              // Цена растения
  "light_condition": "string",    // Требования к свету
  "watering_frequency": "string", // Частота полива
  "temperature_regime": "string", // Температурный режим
  "care_complexity": "string",    // Сложность ухода
  "description": "string",        // Описание растения
  "type": "string",               // Тип растения
  "species": "string",            // Вид растения
  "care_rules": ObjectId(),       // Ссылка на правила ухода за растением
  "created_at": ISODate(),        // Дата добавления растения
}

Добавить тестовых данных в бд

**Comment by AnjeZenda** [comment]
created_at я думаю лучше на сервере создавать

**Comment by AnjeZenda** [comment]
также нужно прокидывать userId который будет продавать цветок
